### ISSUE TITLE
本地测试数据不完整

### ISSUE THREAD

**Issue by AGDholo** [chafan-dev/chafan-frontend#17]
只有首页能正常显示，其他页面都是 404

本地测试用户也无法创建圈子等

**Comment by AGDholo** [comment]
本地测试时，鼠标放上用户名字无法显示 UserCard
![image](https://user-images.githubusercontent.com/13300332/110072784-4978b000-7db9-11eb-8c7d-27ae519d398d.png)

**Comment by izgzhen** [comment]
目前所有 API 都在三个地方定义：

- https://github.com/chafan-dev/chafan-frontend/tree/master/src/api
- https://github.com/chafan-dev/chafan-frontend/blob/master/src/api.ts
- https://github.com/chafan-dev/chafan-frontend/blob/master/src/api2.ts

**Comment by izgzhen** [comment]
如果看 server.js 的话，其中只有静态首页用到的我现在做了 mock

**Comment by izgzhen** [comment]
API 是有类型的，所以原则上可以按类型随便编 mock 用的数据，也可以在 prod 里面用 inspector 截取数据样例（注意尽量要去除个人相关信息再上传）。

**Comment by izgzhen** [comment]
> 本地测试时，鼠标放上用户名字无法显示 UserCard
> ![image](https://user-images.githubusercontent.com/13300332/110072784-4978b000-7db9-11eb-8c7d-27ae519d398d.png)

https://github.com/chafan-dev/chafan-frontend/blob/852521e5bb1df47f48f9af3434ffa796571f13ff/src/components/UserCard.vue#L161-L171 这几个 API 没有实现 mock 导致的

**Comment by izgzhen** [comment]
@AGDholo 另外因为优先级问题，我自己目前没有明确的时间表把 mock 100% 加全，但是如果我打算增加一部分的话会尽快先 merge 进去，如果你要加的话也尽量先开一些小的 PR 弄进去，防止干重复了，多谢！！！

**Comment by AGDholo** [comment]
> @AGDholo 另外因为优先级问题，我自己目前没有明确的时间表把 mock 100% 加全，但是如果我打算增加一部分的话会尽快先 merge 进去，如果你要加的话也尽量先开一些小的 PR 弄进去，防止干重复了，多谢！！！

好！

**Comment by izgzhen** [comment]
放弃了，维护成本太高，现在改成通过设计模块时尽量支持静态渲染来辅助本地测试 UI
