### ISSUE TITLE
[Feature Request]转发模块添加复制到剪切板功能

### ISSUE THREAD

**Issue by AGDholo** [chafan-dev/chafan-frontend#225]
![image](https://user-images.githubusercontent.com/13300332/130742146-1b9042c6-af4b-4a1d-9335-ca647df3a587.png)

类似于知乎这样？
![image](https://user-images.githubusercontent.com/13300332/130742256-0cca7bf5-e9cd-4981-be9e-3f902d185b45.png)

或许可以考虑将复制链接文本变为按钮，点击之后把链接复制到用户剪切板，然后复制内容里面自动加入标题，这样体验效果或许更好一点。

例子：
```
如何看待科技部向全社会征集颠覆性技术研发方向？你有什么脑洞呢？ - 温酒的回答 - 知乎
https://www.zhihu.com/question/481220643/answer/2082917651
```

**Comment by Endle** [comment]
> 或许可以考虑将复制链接文本变为按钮，点击之后把链接复制到用户剪切板，然后复制内容里面自动加入标题，这样体验效果或许更好一点。

这个功能我个人觉得不是很方便。如果要复制到诸如 getpocket 的工具内，还要手动把链接外的部分移除

**Comment by izgzhen** [comment]
已实现哈哈
<img width="726" alt="Screen Shot 2021-11-17 at 22 19 51" src="https://user-images.githubusercontent.com/7168454/142362910-491f3dae-b847-4f1d-b0a0-18a47a0d7e23.png">

**Comment by izgzhen** [comment]
> > 或许可以考虑将复制链接文本变为按钮，点击之后把链接复制到用户剪切板，然后复制内容里面自动加入标题，这样体验效果或许更好一点。
> 
> 这个功能我个人觉得不是很方便。如果要复制到诸如 getpocket 的工具内，还要手动把链接外的部分移除

存到 Pocket 需要特别适配，https://github.com/chafan-dev/chafan-frontend/issues/259 现在应该是完全不兼容的状态。
