### ISSUE TITLE
解决 c-card 的 css 代码重复

### ISSUE THREAD

**Issue by izgzhen** [chafan-dev/chafan-frontend#26]
不知道现在的 project 哪里是最好的拓展 v-card CSS 属性的方法？

**Comment by izgzhen** [comment]
@AGDholo

**Comment by AGDholo** [comment]
我之前尝试在 main.ts 里面引入一个独立的 style.css，但是样式不生效，不知道为什么

**Comment by AGDholo** [comment]
如果在单个 .vue 文件内写的是 <style scoped> 那就只会在当前文件中应用这个类，但是我删掉 scoped 之后全局也不生效，看控制台是有样式但是被覆盖了，很奇怪。

**Comment by izgzhen** [comment]
> 如果在单个 .vue 文件内写的是 <style scoped> 那就只会在当前文件中应用这个类，但是我删掉 scoped 之后全局也不生效，看控制台是有样式但是被覆盖了，很奇怪。

`scoped` 给我的感觉是 bug 重重，很难预测行为。

**Comment by izgzhen** [comment]
> 我之前尝试在 main.ts 里面引入一个独立的 style.css，但是样式不生效，不知道为什么

I see，我还试图在 App.vue 里写，觉得会 propagate 下去...然而并不行。。

**Comment by izgzhen** [comment]
不太懂 webpack 和 vue 里的各种魔法

**Comment by AGDholo** [comment]
正常情况下是可以应用到全局 css 的，不知道里面出了什么问题。
