### ISSUE TITLE
envApiUrl has a http:// prefix 

### ISSUE THREAD

**Issue by Combo819** [chafan-dev/chafan-frontend#260]
In `.env.local`, `VUE_APP_API` has the `https://` prefix
```
VUE_APP_API=https://chafan-test.herokuapp.com
```
and In `src/env.ts`, `envApiUrl` has `http://`
```typescript
  else {
  envApiUrl = `http://${process.env.VUE_APP_API}`;
  envWsUrl = `ws://${process.env.VUE_APP_API}`;
}
```
Then the API request url will be like `http://https//chafan-test.herokuapp.com/api/v1/sitemaps/`

![image](https://user-images.githubusercontent.com/38422065/142468613-b71cd44f-71a2-4c7e-b872-11bc3b583505.png)

**Comment by izgzhen** [comment]
Fixed in https://github.com/chafan-dev/chafan-frontend/commit/a26b47171d945cd748c4ee20859a00bbe73af8dc

Let's use a shared env local to avoid problems like this. Thanks for reporting!!!!
