### ISSUE TITLE
构建时生成当前版本的 git hash

### ISSUE THREAD

**Issue by izgzhen** [chafan-dev/chafan-frontend#3]
可以输出成单独的文件或者包含在某个页面里

**Comment by lynzrand** [comment]
想试试用这个库在编译时获取信息 https://github.com/seymen/git-last-commit

**Comment by izgzhen** [comment]
```
git rev-parse --short=8 --verify HEAD
```

直接跑 git 也行

**Comment by izgzhen** [comment]
这个库 star 太少了，我不太放心（

**Comment by lynzrand** [comment]
![图片](https://user-images.githubusercontent.com/10259119/110763589-058c1c00-828d-11eb-9e2d-19f7f0368552.png)

我这边调出来了，在 `env.ts` 里导出了一个变量。做成什么样式比较好？

**Comment by izgzhen** [comment]
> 做成什么样式比较好？

打算放到哪里？（我在考虑放到某个犄角旮旯没有人注意的地方，用能看见的最小的字体加 `grey--text` 这样。

**Comment by izgzhen** [comment]
<img width="421" alt="Screen Shot 2021-03-11 at 1 29 41 AM" src="https://user-images.githubusercontent.com/7168454/110765655-417d9d80-8209-11eb-90e6-888b83ac0790.png">

感觉也许可以放到 Discord 闲聊群的那个块下面？人们一般看久了应该就不会受到下面一行小字的干扰了。

**Comment by lynzrand** [comment]
> 
> 
> <img alt="Screen Shot 2021-03-11 at 1 29 41 AM" width="421" src="https://user-images.githubusercontent.com/7168454/110765655-417d9d80-8209-11eb-90e6-888b83ac0790.png">
> 
> 感觉也许可以放到 Discord 闲聊群的那个块下面？人们一般看久了应该就不会受到下面一行小字的干扰了。

![图片](https://user-images.githubusercontent.com/10259119/110781109-738e0e80-82a0-11eb-93ae-cee219fca007.png)

**Comment by izgzhen** [comment]
@lynzrand 刚看到最新的回复。。样式可以先这样
