### ISSUE TITLE
设计主题切换功能

### ISSUE THREAD

**Issue by izgzhen** [chafan-dev/chafan-frontend#30]
目前大多数内容已经组件化，不过需要进一步抽象；还需要加入一个 persistent state 记录用户的主题偏好（类似 LangPicker）

**Comment by AGDholo** [comment]
可以先等全部页面重新设计好之后再应用主题，

主题设计的话，最基础的我觉得应该要有 dark & light，现在浏览器也有 api 提供自动根据系统主题来切换亮暗色

**Comment by izgzhen** [comment]
> 可以先等全部页面重新设计好之后再应用主题，

我觉得还比较正交吧？两者可以同时慢慢迭代进行。我想象中应用级的组件（e.g. AnswerPreview）应该大多数会一直存在，只不过组织方式可能有所变化，并不影响定制其样式。

不过我可能只会把一些最基础的 ground work 做好，我应该不会有时间实现新主题。

> 主题设计的话，最基础的我觉得应该要有 dark & light，现在浏览器也有 api 提供自动根据系统主题来切换亮暗色

同意

**Comment by AGDholo** [comment]
> 我觉得还比较正交吧？两者可以同时慢慢迭代进行。我想象中应用级的组件（e.g. AnswerPreview）应该大多数会一直存在，只不过组织方式可能有所变化，并不影响定制其样式。

主题仅仅是变色吗？那应该全局组件只用 primary 这种格式的颜色就行了

**Comment by izgzhen** [comment]
> 主题仅仅是变色吗？那应该全局组件只用 primary 这种格式的颜色就行了

不仅是颜色，比如 Rynco 的稿件里的那个风格，和我们现在的风格，我认为可以当做两种可以互相切换的主题

**Comment by izgzhen** [comment]
> 主题仅仅是变色吗？那应该全局组件只用 primary 这种格式的颜色就行了

而且我认为随便换颜色不换别的其实一般来说会有问题，颜色是样式体验的一部分，得统一设计成一套完整的主题

**Comment by AGDholo** [comment]
> 不仅是颜色，比如 Rynco 的稿件里的那个风格，和我们现在的风格，我认为可以当做两种可以互相切换的主题

这个工作量应该会很大，vuetify 这个库要想高度定制的话有点麻烦

**Comment by izgzhen** [comment]
> 这个工作量应该会很大，vuetify 这个库要想高度定制的话有点麻烦

理想情况下肯定工作量不小，不过这个需求并不急，也不求完美实现设计稿中的样子。

**Comment by lynzrand** [comment]
> 
> 
> 可以先等全部页面重新设计好之后再应用主题，
> 
> 主题设计的话，最基础的我觉得应该要有 dark & light，现在浏览器也有 api 提供自动根据系统主题来切换亮暗色

总之先出了一套 Dark Mode 的色板，基础的亮暗颜色切换问题应该不大，直接用 CSS 变量完成都可以

**Comment by AGDholo** [comment]
vuetify 有内置主题系统，在根 app 上设置 dark 即可转换为暗黑模式

**Comment by izgzhen** [comment]
目前储存主题设置到浏览器 localStorage 中，因为用户的主题风格偏好可能会随着设备改变而有可能不同。

**Comment by izgzhen** [comment]
Related: #112
