### ISSUE TITLE
站外分享链接生成有误

### ISSUE THREAD

**Issue by ksqsf** [chafan-dev/chafan-frontend#34]
例如：

<img width="826" alt="image" src="https://user-images.githubusercontent.com/23358293/110233886-086fcf80-7f62-11eb-9f1c-7d7bf0e7143f.png">

这里的链接前面多了一个 `/` ，点击后访问到了 cha.fan/https://github.com/xxx ，最终会跳转到网站首页。

<del>似乎是这里的问题： https://github.com/chafan-dev/chafan-frontend/blob/master/src/views/main/Submission.vue#L39</del>

（应该是 SubmissionCard 里的 RouterLink 问题

**Comment by izgzhen** [comment]
哦草，我看下，多谢！

**Comment by izgzhen** [comment]
![Screen Shot 2021-03-07 at 1 32 59 AM](https://user-images.githubusercontent.com/7168454/110235480-0e739b00-7ee5-11eb-8285-c971e47052c0.png)

**Comment by izgzhen** [comment]
哦，等下，这个是卡片里的

**Comment by izgzhen** [comment]
我再看下

**Comment by izgzhen** [comment]
啊，确实有问题

**Comment by izgzhen** [comment]
Fixed.
