### ISSUE TITLE
使用 <v-sheet> 替换多余的 <v-card> 来成为基底

### ISSUE THREAD

**Issue by AGDholo** [chafan-dev/chafan-frontend#45]
### 问题说明：

目前存在有很多地方作为基底样式（`<div> <v-sheet>`）的地方使用 <v-card> 来布局。  
这样会导致内部可能无法与整体布局对其，无法直接覆写 vuetify vCard 内部样式（会因为以上情况导致样式重复应用） #26 

### 解决方案：

清理代码并用 `<v-sheet>` 来替换。

**Comment by izgzhen** [comment]
I think this is fixed, thanks!
