### ISSUE TITLE
LightboxGroup 适配图片实际尺寸大小

### ISSUE THREAD

**Issue by izgzhen** [chafan-dev/chafan-frontend#46]
https://github.com/chafan-dev/chafan-frontend/blob/master/src/components/LightboxGroup.vue

太小的时候有问题 e.g. https://cha.fan/questions/3vrbUtcMsSheae3PQy7b

**Comment by AGDholo** [comment]
```html
<v-sheet class="text-center transparent">
  <img src="https://cha.fan/img/icons/favicon-32x32.png" />
 </v-sheet>
```

`<v-img>` 为了图片缩放响应式是直接给 `<div>` 设置的背景，所以会导致缩放，如果要用 `<v-img>` 的话解决办法也很简单，覆写内部 class：`.v-image__image--cover`

![image](https://user-images.githubusercontent.com/13300332/110583439-a8b73580-81a8-11eb-9a4b-27005e677c8b.png)

其他解决方案，服务器内部返回多个分辨率图像，然后进行加载：https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset
