### ISSUE TITLE
是否可以把创建 form 和内容列表放到一起？

### ISSUE THREAD

**Issue by izgzhen** [chafan-dev/chafan-frontend#48]
![image](https://user-images.githubusercontent.com/7168454/110573590-5fb3a280-8110-11eb-8f05-cc9cfc631654.png)

如上图，目前创建列表在右边栏（或者 bottom sheet）里，放到左边对应 tab 的开始（在已有问题/分享列表前）也许更方便直观。

**Comment by izgzhen** [comment]
@lynzrand 你有啥想法没？

**Comment by lynzrand** [comment]
感觉可以把创建按钮放在右边，实际的创建表单放在左栏顶端（

不过提问单开一页可能会更好一点

**Comment by AGDholo** [comment]
相似 demo
![image](https://user-images.githubusercontent.com/13300332/110583775-29763180-81a9-11eb-878a-afb94d31a427.png)

**Comment by AGDholo** [comment]
放在一起可能会干扰用户阅读，
或许可以将提问等按钮统一放到搜索框右侧，

![image](https://user-images.githubusercontent.com/13300332/111290910-95610a00-8681-11eb-8478-5237c6aefb80.png)

**Comment by izgzhen** [comment]
> 放在一起可能会干扰用户阅读，
> 或许可以将提问等按钮统一放到搜索框右侧，
> 
> ![image](https://user-images.githubusercontent.com/13300332/111290910-95610a00-8681-11eb-8478-5237c6aefb80.png)

mobile 里放不下

**Comment by izgzhen** [comment]
也可以考虑在 tab 右侧放？
![Screen Shot 2021-03-16 at 11 03 15](https://user-images.githubusercontent.com/7168454/111358194-50b87d00-8647-11eb-8139-67ae391a93bc.png)

**Comment by izgzhen** [comment]
(非常试探性，我目前没有还没有想到比较满意的方案）
