### ISSUE TITLE
邀请码生成优化

### ISSUE THREAD

**Issue by AGDholo** [chafan-dev/chafan-frontend#49]
### 问题说明

https://cha.fan/invitation-links/

目前是当前窗口跳转的，但是该邀请码展示页面没有任何的回退按钮

![image](https://user-images.githubusercontent.com/13300332/110586788-ac00f000-81ad-11eb-99c1-494b94363be1.png)

### 解决方案

A. 跳转到新标签页
B. 弹出对话框动态生成
C. 添加回退按钮

**Comment by izgzhen** [comment]
Thanks!

**Comment by AGDholo** [comment]
并且邀请码没有任何框框可以填写，前端直接 output 出邀请链接就行了

**Comment by izgzhen** [comment]
Fixed. 目前既可以用链接，也可以在登录界面点击进入注册界面手动填写。
