### ISSUE TITLE
可能由于富文本渲染未工作或引擎更换导致的期望之外的渲染结果

### ISSUE THREAD

**Issue by NeapolitanIcecream** [chafan-dev/chafan-frontend#63]
问题如图，出现在[此问题](https://cha.fan/questions/3a83fCY5nfxrPiuN4pd9?title=%E7%8E%B0%E4%BB%A3%20C%2B%2B%20%E7%BC%96%E8%AF%91%E5%99%A8%E5%AF%B9%E4%B8%B4%E6%97%B6%E5%AF%B9%E8%B1%A1%E5%81%9A%E4%BA%86%E6%80%8E%E6%A0%B7%E7%9A%84%E4%BC%98%E5%8C%96%EF%BC%9F)张震的回答下。

![image](https://user-images.githubusercontent.com/31983334/110900017-0da39480-833d-11eb-99d5-e6cbd4553011.png)

看上去像是 markdown 在渲染代码块时错误地渲染了代码块周围的 HTML 内容。

**Comment by izgzhen** [comment]
多谢反馈！这是我之前来回迁移自己的答案导致的。目前已经通过修改答案格式解决。
