### ISSUE TITLE
每一个 hover mode 的 UserCard 应该尺寸固定

### ISSUE THREAD

**Issue by izgzhen** [chafan-dev/chafan-frontend#86]
![Screen_Shot_2021-03-12_at_20 46 28](https://user-images.githubusercontent.com/7168454/111055409-643acc80-842a-11eb-9b79-9bb749551d14.png)

- 个人简介 `personal_introduction` 如何使其仅显示正好一行宽？
- ”有X个关注者“等属性是否可以简化成 Icon + 数字来缩减所占行数？

**Comment by AGDholo** [comment]
https://vuetifyjs.com/zh-Hans/styles/text-and-typography/#section-6587672c6362884c548c6ea251fa

**Comment by izgzhen** [comment]
> 个人简介 personal_introduction 如何使其仅显示正好一行宽？

我稍微展开一下，需求是：如果比较短，就正常显示。如果太长，截取前面一部分加上 `...` 应该正好一行宽。这样这个部分最多占一行的行高。
