### ISSUE TITLE
个人资料链接不正确

### ISSUE THREAD

**Issue by AGDholo** [chafan-dev/chafan-frontend#92]
#81 

https://github.com/chafan-dev/chafan-frontend/blob/master/src/views/main/Main.vue#L460

当时不用可选链的话，会提示 typescript 类型可能为 null 无法链接到下一个 key，但是增加可选链之后链接就自动变为 `undefined`

**Comment by izgzhen** [comment]
这个需要 mounted 完了更新，construction 时候的太早了

**Comment by izgzhen** [comment]
唉我没有看出来这个 bug

**Comment by izgzhen** [comment]
哥们儿你也要多测测啊 🤦 不是我写的代码我有的时候记不住要测试

**Comment by izgzhen** [comment]
如果测试需要 mock 的话可以提醒我一下

**Comment by izgzhen** [comment]
Fix deployed/

**Comment by AGDholo** [comment]
> 哥们儿你也要多测测啊 🤦 不是我写的代码我有的时候记不住要测试。我得多想想怎么提升下自动化测试的能力

本地的测试数据有些时候搞得我不知道加载错误是因为测试数据不完整，还是因为代码错误

**Comment by izgzhen** [comment]
> > 哥们儿你也要多测测啊 🤦 不是我写的代码我有的时候记不住要测试。我得多想想怎么提升下自动化测试的能力
> 
> 本地的测试数据有些时候搞得我不知道加载错误是因为测试数据不完整，还是因为代码错误

明白了，我会想办法让本地测试更合理一些，prod 上有 bug 也挺常见的 🤦现在也没有太多人用，不用太放心上
